# Generated by Django 2.0.7 on 2018-08-02 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMessage',
            fields=[
                ('bMessageId', models.AutoField(primary_key=True, serialize=False)),
                ('bMessageText', models.CharField(blank=True, max_length=500)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('dateTo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BranchMessageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_last', models.IntegerField(default=1)),
                ('is_first', models.IntegerField(default=1)),
                ('bMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_message', to='Replies.BranchMessage')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('messageText', models.CharField(blank=True, max_length=500)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('dateTo', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MessageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_branched', models.IntegerField(default=0)),
                ('branchMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.BranchMessage')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_message', to='Replies.Message')),
                ('parentMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='Replies.Message')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('orgId', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(blank=True, max_length=255)),
                ('orgAddress', models.CharField(blank=True, max_length=255)),
                ('orgCode', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('subCategory', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectText', models.CharField(blank=True, max_length=500)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('dateTo', models.DateField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.Category')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.Message')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('orgCode', models.CharField(blank=True, max_length=255)),
                ('userName', models.CharField(blank=True, max_length=255)),
                ('userEmail', models.EmailField(blank=True, max_length=255)),
                ('userPassword', models.CharField(blank=True, max_length=255)),
                ('userRole', models.IntegerField(default=1)),
                ('is_active', models.IntegerField(default=1)),
                ('OrgInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.OrgInfo')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.UserInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.UserInfo'),
        ),
        migrations.AddField(
            model_name='branchmessagemetadata',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.Message'),
        ),
        migrations.AddField(
            model_name='branchmessagemetadata',
            name='parentBmessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='Replies.BranchMessage'),
        ),
        migrations.AddField(
            model_name='branchmessage',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Replies.UserInfo'),
        ),
    ]
