# Generated by Django 2.0.7 on 2018-08-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Replies', '0002_auto_20180802_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemetadata',
            old_name='branchMessage',
            new_name='bMessageId',
        ),
    ]
